// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BudgetStatus(arg1) {
  return window['go']['main']['App']['BudgetStatus'](arg1);
}

export function CreateBudget(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateBudget'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteBudget(arg1) {
  return window['go']['main']['App']['DeleteBudget'](arg1);
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function IssueKey(arg1) {
  return window['go']['main']['App']['IssueKey'](arg1);
}

export function ListBudgets() {
  return window['go']['main']['App']['ListBudgets']();
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function ListPricing() {
  return window['go']['main']['App']['ListPricing']();
}

export function ListUsage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListUsage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RevokeKey(arg1) {
  return window['go']['main']['App']['RevokeKey'](arg1);
}

export function SetPricing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPricing'](arg1, arg2, arg3);
}

export function Summary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Summary'](arg1, arg2, arg3, arg4);
}

export function UpdateBudget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBudget'](arg1, arg2, arg3, arg4);
}
