// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {db} from '../models';

export function BudgetStatus(arg1:string):Promise<api.BudgetStatus>;

export function CreateBudget(arg1:string,arg2:string,arg3:string,arg4:db.BudgetPeriod,arg5:number,arg6:number):Promise<db.Budget>;

export function DeleteBudget(arg1:string):Promise<void>;

export function GetAPIURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function IssueKey(arg1:string):Promise<api.IssueKeyResult>;

export function ListBudgets():Promise<Array<db.Budget>>;

export function ListKeys():Promise<Array<db.AgentKey>>;

export function ListPricing():Promise<Array<db.ModelPricing>>;

export function ListUsage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<api.ListUsageResult>;

export function Quit():Promise<void>;

export function RevokeKey(arg1:string):Promise<void>;

export function SetPricing(arg1:string,arg2:number,arg3:number):Promise<db.ModelPricing>;

export function Summary(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.UsageSummary>;

export function UpdateBudget(arg1:string,arg2:any,arg3:any,arg4:any):Promise<db.Budget>;
